"""
测试：数据模型 — 创建与查询
"""
import pytest
from sqlalchemy import select


class TestUserModel:
    @pytest.mark.asyncio
    async def test_create_user(self, db_session):
        from src.models.user import User
        user = User(username="test", email="test@test.com", password_hash="hash")
        db_session.add(user)
        await db_session.flush()

        result = await db_session.execute(select(User).where(User.username == "test"))
        u = result.scalar_one()
        assert u.email == "test@test.com"
        assert u.role == "user"
        assert u.is_active is True

    @pytest.mark.asyncio
    async def test_user_unique_username(self, db_session):
        from src.models.user import User
        u1 = User(username="unique", email="a@a.com", password_hash="h")
        u2 = User(username="unique", email="b@b.com", password_hash="h")
        db_session.add_all([u1, u2])
        with pytest.raises(Exception):
            await db_session.flush()

    @pytest.mark.asyncio
    async def test_user_uuid_autogenerated(self, db_session):
        from src.models.user import User
        user = User(username="uid", email="uid@test.com", password_hash="h")
        db_session.add(user)
        await db_session.flush()
        assert user.id is not None
        assert len(str(user.id)) == 36

    @pytest.mark.asyncio
    async def test_user_timestamps(self, db_session):
        from src.models.user import User
        user = User(username="time", email="time@test.com", password_hash="h")
        db_session.add(user)
        await db_session.flush()
        assert user.created_at is not None
        assert user.updated_at is not None


class TestLawaProfileModel:
    @pytest.mark.asyncio
    async def test_create_profile(self, db_session):
        from src.models.user import User, LawaProfile
        user = User(username="prof", email="prof@test.com", password_hash="h")
        db_session.add(user)
        await db_session.flush()

        profile = LawaProfile(
            user_id=user.id, native_lang="zh", learn_lang="en", total_coins=100,
        )
        db_session.add(profile)
        await db_session.flush()

        result = await db_session.execute(
            select(LawaProfile).where(LawaProfile.user_id == user.id)
        )
        p = result.scalar_one()
        assert p.native_lang == "zh"
        assert p.learn_lang == "en"
        assert p.total_coins == 100
        assert p.consecutive_login_days == 0

    @pytest.mark.asyncio
    async def test_profile_default_values(self, db_session):
        from src.models.user import User, LawaProfile
        user = User(username="def", email="def@test.com", password_hash="h")
        db_session.add(user)
        await db_session.flush()

        profile = LawaProfile(user_id=user.id, native_lang="en", learn_lang="zh")
        db_session.add(profile)
        await db_session.flush()

        assert profile.skills == {}
        assert profile.interests == []
        assert profile.weak_areas == []
        assert profile.can_help == []
        assert profile.total_coins == 0
        assert profile.total_study_minutes == 0

    @pytest.mark.asyncio
    async def test_profile_skills_json(self, db_session):
        from src.models.user import User, LawaProfile
        user = User(username="js", email="js@test.com", password_hash="h")
        db_session.add(user)
        await db_session.flush()

        profile = LawaProfile(
            user_id=user.id,
            native_lang="zh",
            learn_lang="fr",
            skills={"grammar": "B1", "reading": "A2"},
            interests=["music", "travel"],
            weak_areas=["pronunciation"],
            time_preference={"morning": True},
        )
        db_session.add(profile)
        await db_session.flush()

        assert profile.skills["grammar"] == "B1"
        assert "travel" in profile.interests
        assert "pronunciation" in profile.weak_areas


class TestCoinModel:
    @pytest.mark.asyncio
    async def test_create_transaction(self, db_session):
        from uuid import uuid4
        from src.models.coin import CoinTransaction
        uid = uuid4()
        txn = CoinTransaction(user_id=uid, amount=50, type="earn", balance_before=100, balance_after=150, description="完成任务")
        db_session.add(txn)
        await db_session.flush()
        assert txn.amount == 50
        assert txn.type == "earn"
        assert txn.created_at is not None


class TestAssessmentModel:
    @pytest.mark.asyncio
    async def test_create_assessment(self, db_session):
        from uuid import uuid4
        from src.models.assessment import Assessment
        uid = uuid4()
        a = Assessment(
            user_id=uid,
            lang="en",
            overall_level="B1",
            dimension_scores={"grammar": "B1", "vocabulary": "A2"},
        )
        db_session.add(a)
        await db_session.flush()
        assert a.lang == "en"
        assert a.overall_level == "B1"
        assert a.dimension_scores["grammar"] == "B1"
